// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iymlvqlpdsauayedemaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5bWx2cWxwZHNhdWF5ZWRlbWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NjkwMDIsImV4cCI6MjA3NDU0NTAwMn0.Pycu7QAsryQ4h1-b_UHkuOivPv4JpGKtPVoaTcWztIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});